name: savingtracker

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  savingtracker.api:
    build:
      context: .
      dockerfile: SavingTracker.API/Dockerfile
    container_name: savingtracker-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${API_ENVIRONMENT}
      ConnectionStrings__ConnectionString: ${API_CONNECTION_STRING}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  savingtracker.ui:
    build:
      context: .
      dockerfile: SavingTracker.UI/SavingTracker.UI/Dockerfile
    container_name: savingtracker-blazor
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${BLAZOR_ENVIRONMENT}
      ApiBaseUrl: ${BLAZOR_API_BASE_URL}
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - "5000:5000"
    depends_on:
      - savingtracker.api
volumes:
  pgdata: