name: Deploy to Home Server

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Home Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /c/Code/Projects/SavingTracker
          git pull origin main
          docker compose down
          docker compose up -d --build