name: Deploy to Mini PC

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Application
      shell: cmd
      run: |
        cd C:\Code\Projects\SavingTracker
        git pull origin main
        docker compose down
        docker compose up -d --build